### ISSUE TITLE
Travis Service is Failing as of latest

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-system#27]
Haven't investigated this much, but here is the log 

```
2016-04-04T01:19:21.557Z uqetd5j4yuis/1459732761476/43034/- INFO    hello   Seneca/2.0.0/uqetd5j4yuis/1459732761476/43034/- 
2016-04-04T01:19:24.140Z uqetd5j4yuis/1459732761476/43034/- INFO    listen  {pin:[role:travis,role:info,req:part],model:publish}    
2016-04-04T01:19:24.965Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:info,cmd:get,model:publish}  
2016-04-04T01:19:24.967Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:info,res:*,model:publish}    
2016-04-04T01:19:24.970Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:info, info:updated,model:publish}    
2016-04-04T01:19:24.971Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:npm,model:publish}   
2016-04-04T01:19:24.973Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:search,cmd:upsert,model:consume} 
2016-04-04T01:19:24.975Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:github,model:publish}    
2016-04-04T01:19:24.978Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:null:true,model:actor}    
2016-04-04T01:19:24.981Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:mesh,base:true,model:actor}  
2016-04-04T01:19:24.983Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:search,cmd:search,model:consume} 
2016-04-04T01:19:24.985Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT azlk9rsz2lrm/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:57208,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:24.987Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT eu5o7d69189a/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:57208,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:24.988Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT um3yv54xbujx/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:57208,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:24.990Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT o5zozn20plrk/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:54465,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:24.992Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT hl229aawlq7y/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:55075,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:24.993Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT 8wf5wgww69bf/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:52503,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:24.995Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT n4gqwea8b95d/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {port:54853,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen} 
2016-04-04T01:19:24.997Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT 1nr4s14m6q1w/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:54823,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:25.000Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT 2qsb4f9r3uvz/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:56215,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:25.696Z uqetd5j4yuis/1459732761476/43034/- INFO    client  {type:balance,pin:role:info,info:updated,model:observe} 
2016-04-04T01:19:25.701Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT vxj17k76zlsv/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:53141,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:25.703Z uqetd5j4yuis/1459732761476/43034/- INFO    -   -   ACT zhpvao9q3duc/wioyxrko6lu3   name:mesh,plugin:define,role:seneca,seq:7,tag:undefined plugin  mesh        ACT allym71v9mtw/bnvmcm00pwt0   add:client,role:transport,type:balance  client  {type:web,port:53141,host:0.0.0.0,path:/act,protocol:http,timeout:5555,max_listen_attempts:11,attempt_delay:222 
2016-04-04T01:19:42.248Z uqetd5j4yuis/1459732761476/43034/- FATAL   -   -   ACT cf6gmm5ui7kv/jbdmjzv0wfne   name:travis,plugin:define,role:seneca,seq:6,tag:undefined   plugin  travis          sys seneca  2.0.0   uqetd5j4yuis/1459732761476/43034/-  act_not_found   seneca: No matching action pattern found for { data:    { name: 'lodash',     id: 48500,     slug: 'lodash/lodash',     active: true,     description: 'A modern JavaScript utility library delivering modularity, performance, & extras.',     last_build_id: 120342337,     last_build_number: '4371',     last_build_state: 'passed',     last_build_duration: 2288,     last_build_language: null,     last_build_started_at: '2016-04-02T22:00:53Z',     last_build_finished_at: '2016-04-02T22:18:28Z',     github_language: 'JavaScript',     language: 'node_js',     sudo: false,     node_js: [ '5' ],     env: [ '', 'BIN="phantomjs"', 'ISTANBUL=true', 'SAUCE_LABS=true' ],     matrix: { include: [Object] },     git: { depth: 10 },     branches: { only: [Object] },     notifications: { webhooks: [Object] },     before_install:       [ 'nvm use $TRAVIS_NODE_VERSION',        'npm set loglevel error',        'npm set progress false',        'npm i -g npm@"^2.0.0"',        'PATTERN[0]="|\\s*if\\s*\\(isHostObject\\b[\\s\\S]+?\\}(?=\\n)|"\nPATTERN[1]="|\\s*if\\s*\\(enumerate\\b[\\s\\S]+?\\};\\s*\\}|"\nPATTERN[2]="|\\s*while\\s*\\([^)]+\\)\\s*\\{\\s*iteratee\\(index\\);\\s*\\}|"\nPATTERN[3]="|\\s*else\\s*\\{\\s*assocSet\\(data\\b[\\s\\S]+?\\}|"\nPATTERN[4]="|\\bcase\\s+(?:dataView|set|map|weakMap)CtorString:.+|g"\nPATTERN[5]="|\\bindex,\\s*iterable\\)\\s*===\\s*false\\)[^}]+?(break;)|"\nPATTERN[6]="|\\s*if\\s*\\(\\!lodashFunc\\)\\s*\\{\\s*return;\\s*\\}|"\nPATTERN[7]="|\\s*define\\([\\s\\S]+?\\);|"\nPATTERN[8]="|\\s*root\\._\\s*=\\s*_;|"\n\nif [ $ISTANBUL == true ]; then\n  set -e\n  for PTRN in ${PATTERN[@]}; do\n    node ./test/remove.js "$PTRN" ./lodash.js\n  done\nfi\n',        'git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli && mkdir $_/node_modules && cd $_ && ln -s ../../../ ./lodash && cd ../ && npm i && cd ../../',        'node ./node_modules/lodash-cli/bin/lodash -o ./dist/lodash.js' ],     script:       [ '[ $ISTANBUL == false ]   || istanbul cover -x "**/vendor/**" --report lcovonly ./test/test.js -- ./lodash.js',        '[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/lcov.info | coveralls) || true',        '[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/coverage.json | codecov) || true',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || cd ./test',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || $BIN $OPTION ./test.js ../lodash.js',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || [ $TRAVIS_SECURE_ENV_VARS == false ] || $BIN $OPTION ./test.js ../dist/lodash.min.js',        '[ $SAUCE_LABS == false ] || rm -rf ./node_modules/lodash',        '[ $SAUCE_LABS == false ] || ($BIN ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./node_modules/lodash && node ./node_modules/lodash-cli/bin/lodash -d -o ./node_modules/lodash/lodash.js)',        '[ $SAUCE_LABS == false ] || $BIN ./node_modules/lodash-cli/bin/lodash core -o ./dist/lodash.core.js',        '[ $SAUCE_LABS == false ] || npm run build',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash tests"     runner="test/index.html?build=../dist/lodash.js&noglobals=true"     tags="development"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash tests"     runner="test/index.html?build=../dist/lodash.min.js&noglobals=true" tags="production"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash-fp tests"  runner="test/fp.html?noglobals=true"                                tags="development"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="underscore tests" runner="test/underscore.html?build=../dist/lodash.js"               tags="development,underscore"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="underscore tests" runner="test/underscore.html?build=../dist/lodash.min.js"           tags="production,underscore"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.js"                 tags="development,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.min.js"             tags="production,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.core.js"            tags="development,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.core.min.js"        tags="production,backbone"' ],     '.result': 'configured',     global_env:       [ 'BIN="node" ISTANBUL=false OPTION=""',        'SAUCE_LABS=false SAUCE_USERNAME="lodash"',        [Object] ],     group: 'stable',     dist: 'precise',     'id$': 'lodash' },  role: 'search',  cmd: 'insert' }, and no default result provided (using a default$ property).   {args:{ data:    { name: 'lodash',     id: 48500,     slug: 'lodash/lodash',     active: true,     description: all-errors-fatal    
2016-04-04T01:19:45.259Z uqetd5j4yuis/1459732761476/43034/- FATAL   -   -   ACT cf6gmm5ui7kv/jbdmjzv0wfne   name:travis,plugin:define,role:seneca,seq:6,tag:undefined   plugin  travis          sys seneca  2.0.0   uqetd5j4yuis/1459732761476/43034/-  act_not_found   seneca: No matching action pattern found for { data:    { name: 'lodash',     id: 48500,     slug: 'lodash/lodash',     active: true,     description: 'A modern JavaScript utility library delivering modularity, performance, & extras.',     last_build_id: 120342337,     last_build_number: '4371',     last_build_state: 'passed',     last_build_duration: 2288,     last_build_language: null,     last_build_started_at: '2016-04-02T22:00:53Z',     last_build_finished_at: '2016-04-02T22:18:28Z',     github_language: 'JavaScript',     language: 'node_js',     sudo: false,     node_js: [ '5' ],     env: [ '', 'BIN="phantomjs"', 'ISTANBUL=true', 'SAUCE_LABS=true' ],     matrix: { include: [Object] },     git: { depth: 10 },     branches: { only: [Object] },     notifications: { webhooks: [Object] },     before_install:       [ 'nvm use $TRAVIS_NODE_VERSION',        'npm set loglevel error',        'npm set progress false',        'npm i -g npm@"^2.0.0"',        'PATTERN[0]="|\\s*if\\s*\\(isHostObject\\b[\\s\\S]+?\\}(?=\\n)|"\nPATTERN[1]="|\\s*if\\s*\\(enumerate\\b[\\s\\S]+?\\};\\s*\\}|"\nPATTERN[2]="|\\s*while\\s*\\([^)]+\\)\\s*\\{\\s*iteratee\\(index\\);\\s*\\}|"\nPATTERN[3]="|\\s*else\\s*\\{\\s*assocSet\\(data\\b[\\s\\S]+?\\}|"\nPATTERN[4]="|\\bcase\\s+(?:dataView|set|map|weakMap)CtorString:.+|g"\nPATTERN[5]="|\\bindex,\\s*iterable\\)\\s*===\\s*false\\)[^}]+?(break;)|"\nPATTERN[6]="|\\s*if\\s*\\(\\!lodashFunc\\)\\s*\\{\\s*return;\\s*\\}|"\nPATTERN[7]="|\\s*define\\([\\s\\S]+?\\);|"\nPATTERN[8]="|\\s*root\\._\\s*=\\s*_;|"\n\nif [ $ISTANBUL == true ]; then\n  set -e\n  for PTRN in ${PATTERN[@]}; do\n    node ./test/remove.js "$PTRN" ./lodash.js\n  done\nfi\n',        'git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli && mkdir $_/node_modules && cd $_ && ln -s ../../../ ./lodash && cd ../ && npm i && cd ../../',        'node ./node_modules/lodash-cli/bin/lodash -o ./dist/lodash.js' ],     script:       [ '[ $ISTANBUL == false ]   || istanbul cover -x "**/vendor/**" --report lcovonly ./test/test.js -- ./lodash.js',        '[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/lcov.info | coveralls) || true',        '[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/coverage.json | codecov) || true',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || cd ./test',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || $BIN $OPTION ./test.js ../lodash.js',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || [ $TRAVIS_SECURE_ENV_VARS == false ] || $BIN $OPTION ./test.js ../dist/lodash.min.js',        '[ $SAUCE_LABS == false ] || rm -rf ./node_modules/lodash',        '[ $SAUCE_LABS == false ] || ($BIN ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./node_modules/lodash && node ./node_modules/lodash-cli/bin/lodash -d -o ./node_modules/lodash/lodash.js)',        '[ $SAUCE_LABS == false ] || $BIN ./node_modules/lodash-cli/bin/lodash core -o ./dist/lodash.core.js',        '[ $SAUCE_LABS == false ] || npm run build',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash tests"     runner="test/index.html?build=../dist/lodash.js&noglobals=true"     tags="development"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash tests"     runner="test/index.html?build=../dist/lodash.min.js&noglobals=true" tags="production"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash-fp tests"  runner="test/fp.html?noglobals=true"                                tags="development"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="underscore tests" runner="test/underscore.html?build=../dist/lodash.js"               tags="development,underscore"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="underscore tests" runner="test/underscore.html?build=../dist/lodash.min.js"           tags="production,underscore"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.js"                 tags="development,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.min.js"             tags="production,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.core.js"            tags="development,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.core.min.js"        tags="production,backbone"' ],     '.result': 'configured',     global_env:       [ 'BIN="node" ISTANBUL=false OPTION=""',        'SAUCE_LABS=false SAUCE_USERNAME="lodash"',        [Object] ],     group: 'stable',     dist: 'precise',     'id$': 'lodash' },  role: 'search',  cmd: 'insert' }, and no default result provided (using a default$ property).   {args:{ data:    { name: 'lodash',     id: 48500,     slug: 'lodash/lodash',     active: true,     description: all-errors-fatal    
2016-04-04T01:19:53.363Z uqetd5j4yuis/1459732761476/43034/- ERROR   act -           OUT     -   11122   {data:{name:lodash,id:48500,slug:lodash/lodash,active:true,description:A modern JavaScript utility library deli ENTRY       -   seneca: Action undefined failed: [TIMEOUT:swvvnisx58zf/jbdmjzv0wfne:11111<1459732793360-1459732782243:undefined].   act_execute {id:swvvnisx58zf/jbdmjzv0wfne,gate:false,ungate:true,desc:null,fn:null,time:{start:1459732782243,end:1459732793 Error: [TIMEOUT:swvvnisx58zf/jbdmjzv0wfne:11111<1459732793360-1459732782243:undefined]
    at null._onTimeout (/Users/gege/nearform/nodezoo-system/node_modules/nodezoo-travis/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)
    at Timer.listOnTimeout (timers.js:92:15)    
2016-04-04T01:19:53.364Z uqetd5j4yuis/1459732761476/43034/- FATAL   -   -   ACT cf6gmm5ui7kv/jbdmjzv0wfne   name:travis,plugin:define,role:seneca,seq:6,tag:undefined   plugin  travis          sys seneca  2.0.0   uqetd5j4yuis/1459732761476/43034/-  act_execute seneca: Action undefined failed: [TIMEOUT:swvvnisx58zf/jbdmjzv0wfne:11111<1459732793360-1459732782243:undefined].   {id:swvvnisx58zf/jbdmjzv0wfne,gate:false,ungate:true,desc:null,fn:null,time:{start:1459732782243,end:1459732793 all-errors-fatal    


Seneca Fatal Error
==================

Message: seneca: No matching action pattern found for { data:    { name: 'lodash',     id: 48500,     slug: 'lodash/lodash',     active: true,     description: 'A modern JavaScript utility library delivering modularity, performance, & extras.',     last_build_id: 120342337,     last_build_number: '4371',     last_build_state: 'passed',     last_build_duration: 2288,     last_build_language: null,     last_build_started_at: '2016-04-02T22:00:53Z',     last_build_finished_at: '2016-04-02T22:18:28Z',     github_language: 'JavaScript',     language: 'node_js',     sudo: false,     node_js: [ '5' ],     env: [ '', 'BIN="phantomjs"', 'ISTANBUL=true', 'SAUCE_LABS=true' ],     matrix: { include: [Object] },     git: { depth: 10 },     branches: { only: [Object] },     notifications: { webhooks: [Object] },     before_install:       [ 'nvm use $TRAVIS_NODE_VERSION',        'npm set loglevel error',        'npm set progress false',        'npm i -g npm@"^2.0.0"',        'PATTERN[0]="|\\s*if\\s*\\(isHostObject\\b[\\s\\S]+?\\}(?=\\n)|"\nPATTERN[1]="|\\s*if\\s*\\(enumerate\\b[\\s\\S]+?\\};\\s*\\}|"\nPATTERN[2]="|\\s*while\\s*\\([^)]+\\)\\s*\\{\\s*iteratee\\(index\\);\\s*\\}|"\nPATTERN[3]="|\\s*else\\s*\\{\\s*assocSet\\(data\\b[\\s\\S]+?\\}|"\nPATTERN[4]="|\\bcase\\s+(?:dataView|set|map|weakMap)CtorString:.+|g"\nPATTERN[5]="|\\bindex,\\s*iterable\\)\\s*===\\s*false\\)[^}]+?(break;)|"\nPATTERN[6]="|\\s*if\\s*\\(\\!lodashFunc\\)\\s*\\{\\s*return;\\s*\\}|"\nPATTERN[7]="|\\s*define\\([\\s\\S]+?\\);|"\nPATTERN[8]="|\\s*root\\._\\s*=\\s*_;|"\n\nif [ $ISTANBUL == true ]; then\n  set -e\n  for PTRN in ${PATTERN[@]}; do\n    node ./test/remove.js "$PTRN" ./lodash.js\n  done\nfi\n',        'git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli && mkdir $_/node_modules && cd $_ && ln -s ../../../ ./lodash && cd ../ && npm i && cd ../../',        'node ./node_modules/lodash-cli/bin/lodash -o ./dist/lodash.js' ],     script:       [ '[ $ISTANBUL == false ]   || istanbul cover -x "**/vendor/**" --report lcovonly ./test/test.js -- ./lodash.js',        '[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/lcov.info | coveralls) || true',        '[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/coverage.json | codecov) || true',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || cd ./test',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || $BIN $OPTION ./test.js ../lodash.js',        '[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || [ $TRAVIS_SECURE_ENV_VARS == false ] || $BIN $OPTION ./test.js ../dist/lodash.min.js',        '[ $SAUCE_LABS == false ] || rm -rf ./node_modules/lodash',        '[ $SAUCE_LABS == false ] || ($BIN ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./node_modules/lodash && node ./node_modules/lodash-cli/bin/lodash -d -o ./node_modules/lodash/lodash.js)',        '[ $SAUCE_LABS == false ] || $BIN ./node_modules/lodash-cli/bin/lodash core -o ./dist/lodash.core.js',        '[ $SAUCE_LABS == false ] || npm run build',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash tests"     runner="test/index.html?build=../dist/lodash.js&noglobals=true"     tags="development"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash tests"     runner="test/index.html?build=../dist/lodash.min.js&noglobals=true" tags="production"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="lodash-fp tests"  runner="test/fp.html?noglobals=true"                                tags="development"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="underscore tests" runner="test/underscore.html?build=../dist/lodash.js"               tags="development,underscore"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="underscore tests" runner="test/underscore.html?build=../dist/lodash.min.js"           tags="production,underscore"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.js"                 tags="development,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.min.js"             tags="production,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.core.js"            tags="development,backbone"',        '[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name="backbone tests"   runner="test/backbone.html?build=../dist/lodash.core.min.js"        tags="production,backbone"' ],     '.result': 'configured',     global_env:       [ 'BIN="node" ISTANBUL=false OPTION=""',        'SAUCE_LABS=false SAUCE_USERNAME="lodash"',        [Object] ],     group: 'stable',     dist: 'precise',     'id$': 'lodash' },  role: 'search',  cmd: 'insert' }, and no default result provided (using a default$ property).

Code: act_not_found

Details: { args: '{ data:    { name: \'lodash\',     id: 48500,     slug: \'lodash/lodash\',     active: true,     description: \'A modern JavaScript utility library delivering modularity, performance, & extras.\',     last_build_id: 120342337,     last_build_number: \'4371\',     last_build_state: \'passed\',     last_build_duration: 2288,     last_build_language: null,     last_build_started_at: \'2016-04-02T22:00:53Z\',     last_build_finished_at: \'2016-04-02T22:18:28Z\',     github_language: \'JavaScript\',     language: \'node_js\',     sudo: false,     node_js: [ \'5\' ],     env: [ \'\', \'BIN="phantomjs"\', \'ISTANBUL=true\', \'SAUCE_LABS=true\' ],     matrix: { include: [Object] },     git: { depth: 10 },     branches: { only: [Object] },     notifications: { webhooks: [Object] },     before_install:       [ \'nvm use $TRAVIS_NODE_VERSION\',        \'npm set loglevel error\',        \'npm set progress false\',        \'npm i -g npm@"^2.0.0"\',        \'PATTERN[0]="|\\\\s*if\\\\s*\\\\(isHostObject\\\\b[\\\\s\\\\S]+?\\\\}(?=\\\\n)|"\\nPATTERN[1]="|\\\\s*if\\\\s*\\\\(enumerate\\\\b[\\\\s\\\\S]+?\\\\};\\\\s*\\\\}|"\\nPATTERN[2]="|\\\\s*while\\\\s*\\\\([^)]+\\\\)\\\\s*\\\\{\\\\s*iteratee\\\\(index\\\\);\\\\s*\\\\}|"\\nPATTERN[3]="|\\\\s*else\\\\s*\\\\{\\\\s*assocSet\\\\(data\\\\b[\\\\s\\\\S]+?\\\\}|"\\nPATTERN[4]="|\\\\bcase\\\\s+(?:dataView|set|map|weakMap)CtorString:.+|g"\\nPATTERN[5]="|\\\\bindex,\\\\s*iterable\\\\)\\\\s*===\\\\s*false\\\\)[^}]+?(break;)|"\\nPATTERN[6]="|\\\\s*if\\\\s*\\\\(\\\\!lodashFunc\\\\)\\\\s*\\\\{\\\\s*return;\\\\s*\\\\}|"\\nPATTERN[7]="|\\\\s*define\\\\([\\\\s\\\\S]+?\\\\);|"\\nPATTERN[8]="|\\\\s*root\\\\._\\\\s*=\\\\s*_;|"\\n\\nif [ $ISTANBUL == true ]; then\\n  set -e\\n  for PTRN in ${PATTERN[@]}; do\\n    node ./test/remove.js "$PTRN" ./lodash.js\\n  done\\nfi\\n\',        \'git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli && mkdir $_/node_modules && cd $_ && ln -s ../../../ ./lodash && cd ../ && npm i && cd ../../\',        \'node ./node_modules/lodash-cli/bin/lodash -o ./dist/lodash.js\' ],     script:       [ \'[ $ISTANBUL == false ]   || istanbul cover -x "**/vendor/**" --report lcovonly ./test/test.js -- ./lodash.js\',        \'[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/lcov.info | coveralls) || true\',        \'[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/coverage.json | codecov) || true\',        \'[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || cd ./test\',        \'[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || $BIN $OPTION ./test.js ../lodash.js\',        \'[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || [ $TRAVIS_SECURE_ENV_VARS == false ] || $BIN $OPTION ./test.js ../dist/lodash.min.js\',        \'[ $SAUCE_LABS == false ] || rm -rf ./node_modules/lodash\',        \'[ $SAUCE_LABS == false ] || ($BIN ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./node_modules/lodash && node ./node_modules/lodash-cli/bin/lodash -
```

**Comment by mcdonnelldean** [comment]
@matt-oc When you remove the rogue patterns from Github / Npm / Travis can you close this?

**Comment by matt-oc** [comment]
@mcdonnelldean Will do, this doesn't just apply to Travis, they all fail in the same way

**Comment by mcdonnelldean** [comment]
@matt-oc Yup :( Some handle it better than others but the root issue is the same

**Comment by matt-oc** [comment]
fixed!
