### ISSUE TITLE
nodezoo-search times out

### ISSUE THREAD

**Issue by bastianwegge** [nodezoo/nodezoo-system#42]
Hey guys,

just wanted to let you know that, after following the instructions on how to start the nodezoo-system I ran into the following problem:

``` shell
-   seneca: Action cmd:search,role:search failed: [TIMEOUT:c73vrxhp4mts/ykzt7ocwsuif:11111<1461420850341-1461420839227:undefined].  act_execute {id:c73vrxhp4mts/ykzt7ocwsuif,gate:false,ungate:true,desc:null,time:{start:1461420839227,end:1461420850341},mes Error: [TIMEOUT:c73vrxhp4mts/ykzt7ocwsuif:11111<1461420850341-1461420839227:undefined]
    at null._onTimeout (/*/seneca/nodezoo/nodezoo-system/node_modules/nodezoo-search/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)
    at Timer.listOnTimeout (timers.js:92:15)    
2016-04-23T14:14:24.948Z g22yyyrmhnd9/1461420834101/1027/nodezoo-search ERROR   -   -   ACT 9zkcdpa1d7hc/y1q79nigrz08   name:seneca-0bjfsr,plugin:define,role:seneca,seq:5,tag:undefined    plugin  nodezoo-search  {status:408,displayName:RequestTimeout,message:Request Timeout after 30000ms}
```

I don't know exactly what's going on as I'm currently learning how to interact with seneca, but this seems a bit odd.

Kind regards

**Comment by Georgette** [comment]
Hi Bastian,

I'd like to debug this with you. So, the nodezoo-search is reliant on elasticsearch to be running, and this should have been set up by following the docker instructions. Can you do this for me?

In `/nodezoo-system`, can you do a `docker ps` and insure that you have output similar to this, and not a `cannot connect to docker daemon`

```
3fb3ba129468        redis               "/entrypoint.sh redis"   2 weeks ago         Up 54 seconds       0.0.0.0:6379->6379/tcp                           fuge_redis_1
286616b8ba9a        elasticsearch       "/docker-entrypoint.s"   2 weeks ago         Up 54 seconds       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   fuge_elastic_search_1
```

If you are getting the error, and you've followed the installation instructions (which outlines getting docker containers set up and started), do a `eval $(docker-machine env default)` in `/nodezoo-system` 

It may not be docker, but just in case. Is the process crashing in fuge?

**Comment by bastianwegge** [comment]
I'm positive that both containers where up and running, here's the shell excerpt after exiting.

``` shell
~/d/c/s/n/nodezoo-system (master) $ d ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
83e5299a1366        elasticsearch       "/docker-entrypoint.s"   5 minutes ago       Exited (143) 14 seconds ago                       fuge_elastic_search_1
488c392a1b91        redis               "docker-entrypoint.sh"   7 minutes ago       Exited (0) 14 seconds ago                         fuge_redis_1
```

I'm back in about 2 hours, maybe we can have a chat about this in the senecajs gitter channel? Or reach me via skype (bastianwegge).

**Comment by mcdonnelldean** [comment]
@bastianwegge we have a gitter channel for nodezoo here. https://gitter.im/nodezoo/nodezoo-org I'm not available over the weekend but between @Georgette and others there may be someone to help you out. If any improvements need to be made to the docs to clarify anything once you get going please let us know!
